name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)

trigger:
  - none

pr:
  - none

jobs:
  - job: Deploy
    displayName: "Deploy Environment"

    steps:
      - checkout: self

      - task: AzureCLI@2
        displayName: "Run Bicep Validate"
        env:
          JOB_STEPNAME: "BicepValidate"
          WORKSPACE_PATH: $(System.DefaultWorkingDirectory)
          RUN_ID: $(Build.BuildId)
        inputs:
          scriptType: bash
          scriptLocation: scriptPath
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts"
          scriptPath: "$(System.DefaultWorkingDirectory)/scripts/bicep_validate.sh"

      - task: AzureCLI@2
        displayName: "Run Bicep Deploy"
        env:
          JOB_STEPNAME: "BicepDeploy"
          WORKSPACE_PATH: $(System.DefaultWorkingDirectory)
          RUN_ID: $(Build.BuildId)
        inputs:
          scriptType: bash
          scriptLocation: scriptPath
          workingDirectory: "$(System.DefaultWorkingDirectory)/scripts"
          scriptPath: "$(System.DefaultWorkingDirectory)/scripts/bicep_deploy.sh"
