name: "Main Workflow"

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: "Deploy Environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Validate
        env:
          JOB_STEPNAME: "BicepValidate"
          WORKSPACE_PATH: ${{ github.workspace }}
          RUN_ID: ${{ github.sha }}
          LOCATION_NAME: "westus2"
        run: |
          echo ${JOB_STEPNAME}
        working-directory: scripts
        shell: bash

      - name: Deploy
        env:
          JOB_STEPNAME: "BicepDeploy"
          WORKSPACE_PATH: ${{ github.workspace }}
          RUN_ID: ${{ github.sha }}
          LOCATION_NAME: "westus2"
        run: |
          echo ${JOB_STEPNAME}
        working-directory: scripts
        shell: bash
